### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by tomasro** [Madj42/ryobi_gdo3#6]
This error caused the GDO to no longer work, after 3 great days of operation...

Logger: homeassistant.components.cover
Source: custom_components/ryobi_gdo3/py_ryobi_gdo.py:90
Integration: Cover (documentation, issues)
First occurred: 2:08:51 AM (1 occurrences)
Last logged: 2:08:51 AM

Error while setting up ryobi_gdo3 platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/ryobi_gdo3/cover.py", line 52, in setup_platform
    if my_door.check_device_id() is False:
  File "/config/custom_components/ryobi_gdo3/py_ryobi_gdo.py", line 90, in check_device_id
    if len(result) == 0:
UnboundLocalError: local variable 'result' referenced before assignment

**Comment by Madj42** [comment]
I didn't get notified of this back when you put this in.  Are you having these issues still?
